### PR TITLE
Reworked the scene system to be more C++ style

### PR DESCRIPTION
**Pull request by ctxnop**
Scene system is now a polymorphic class so that inputs are not globally
checked, but locally to the scene it self. This mean less complexity and
les CPU cycles wasted.

Added a special handling for the svcSleepThread function that fails to
be linked inside a virtual method, don't know why.

Compiled and tested on a ReiNX 4.0.1 switch.

Change-Id: I26ef85b254ec5e5773d81b4c4573670839d9ca94

### CODE REVIEW

**Comment by ctxnop** [comment]
I closed the pull request because the last commit compiles but is not yet tested.

**Comment by ctxnop** [comment]
Now it's tested

**Comment by AnalogMan151** [comment]
Tested and working fine! It's certainly looking more structured and actually like a C++ app now. I'm trying to follow along with your changes as you pull them I'll admit some of them are starting to go over my head.

**Comment by ctxnop** [comment]
I understand that changes can be a bit hard to understand right now, but this is because it's still not real C++. Mixing C and C++ is really a bad thing for readability. Once everything will be in pure C++ it will be easy to understand and follow.

The next change I'm working on is quiet big as well and it still about the frame rendering system.
Getting rid of all those globals is a hard job and it imply to rewrite a lot of things. But once done, you end up with a reusable, testable and simple API. No hidden dependencies, easy to use in a multi thread context if needed, etc...

**Pull request merged**
